version: 1.2.4

cache: true

fileStrategy: "s3"
interface:
  mcpServers:
    placeholder: "MCP Servers"
  modelSelect: true
  parameters: true
  sidePanel: true
  presets: true
  prompts: true
  bookmarks: true
  multiConvo: true
  agents: true
  customWelcome: "Hey {{user.name}}! Welcome to USA-RS's AI"
  runCode: true
  webSearch: true
  fileSearch: true
  fileCitations: true

endpoints:
  all:
    titleConvo: true
    titleEndpoint: "openAI"
    titleModel: "gpt-5-mini"
  agents:
    recursionLimit: 100
    maxRecursionLimit: 200


